version: "3.9"

services:
  garage-door-api:
    build: .
    container_name: garage-door-api
    ports:
      - "8000:8000"
    environment:
      - ADB_DEVICE=${ADB_DEVICE:-auto}
      - CONFIG_PATH=/app/config/phones.yaml
      - DOOR_CODE=${DOOR_CODE:-4}
      - PHONE_SERIAL=${PHONE_SERIAL:-qwerty123456qwerty123456}
      - PHONE_NUMBER=${PHONE_NUMBER:-5551234567}
      - WAIT_AFTER_DIAL_S=${WAIT_AFTER_DIAL_S:-16}
    volumes:
      - ./config:/app/config:ro
    devices:
      - /dev/bus/usb:/dev/bus/usb
    privileged: true
    restart: unless-stopped
