---

services:
  garage-door-api:
    container_name: 'garage-door-api'
    build:
      context: .
      dockerfile: 'Dockerfile'
    image: babico/garage-door-api
    ports:
      - '8000:8000'
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '10'
    healthcheck:
      test: [ 'CMD', 'curl', '--fail', '--silent', 'http://localhost:8000/health' ]
      interval: '30s'
      retries: 3
      start_period: '10s'
      timeout: '10s'
    environment:
      - 'CONFIG_PATH=/app/config/phones.yaml'
      - 'DOOR_CODE=${DOOR_CODE:-4}'
      - 'PHONE_SERIAL=${PHONE_SERIAL:-qwerty123456qwerty123456}'
      - 'PHONE_NUMBER=${PHONE_NUMBER:-5551234567}'
      - 'WAIT_AFTER_DIAL_S=${WAIT_AFTER_DIAL_S:-16}'
    volumes:
      - './config:/app/config:ro'
    devices:
      - '/dev/bus/usb:/dev/bus/usb'
    privileged: true
    restart: 'always'
